### ISSUE TITLE
Setup cybernode clusters in GCS

### ISSUE THREAD

**Issue by cyborgshead** [bro-n-bro/cybernode#10]

**Comment by abitrolly** [comment]
`wechain` cluster is with 4 nodes in `us-central-a`, each node is 2 CPU, 7.5 GB memory (`n1-standard-2`) for running chains. Storage is not attached yet.

**Comment by abitrolly** [comment]
* [x] add disk SSD 1Gb through Compute storage in `us-central-a`
* [x] requested quota increase `500Mb -> 4Gb` for SSD persistent disk in `us-central-a`
* [x] added `chaindata` persistent disk 1Gb
* [ ] add `chaindata` to `wechain` cluster
