### ISSUE TITLE
Mars failures

### ISSUE THREAD

**Issue by abitrolly** [bro-n-bro/cybernode#13]
We are still having problems with Ubuntu 16.04 and Mars https://github.com/cyberFund/cybernode-archive/issues/114

Yesterday docker hung, completely stopped to respond, so @hleb-albau sent the whole system to reboot, but today it appears that OS failed to reboot.

**Comment by abitrolly** [comment]
![image](https://user-images.githubusercontent.com/8781107/36472187-1540c9d8-1702-11e8-8cae-6bd35fb5f18b.png)

![image](https://user-images.githubusercontent.com/8781107/36472207-293d7f80-1702-11e8-8c4c-0c0e18717807.png)

**Comment by hleb-albau** [comment]
Not using mars anymore.
