### ISSUE TITLE
Errors during up.sh

### ISSUE THREAD

**Issue by mastercyb** [bro-n-bro/cybernode#14]
<img width="695" alt="screen shot 2018-02-23 at 11 43 20" src="https://user-images.githubusercontent.com/410789/36578313-dd26f494-188e-11e8-8b70-40d848844c6a.png">

**Comment by mastercyb** [comment]
<img width="896" alt="screen shot 2018-02-23 at 11 54 26" src="https://user-images.githubusercontent.com/410789/36578527-5a272a62-1890-11e8-92de-99d7bd9bb722.png">
Failed to launch cybernode. 

@litvintech seems that I need to give permission to some folder (using docker) but I don't understand which one. If so this step should be documented

**Comment by hleb-albau** [comment]
Right now we have only k8s services definitions. Old script is deprecated and deleted.
