### ISSUE TITLE
Basic research of IPFS's scalability and performance

### ISSUE THREAD

**Issue by cyborgshead** [bro-n-bro/cybernode#21]

**Comment by cyborgshead** [comment]
@hleb-albau @Pechalka 
Basic information
[awesome-ipfs](https://github.com/ipfs/awesome-ipfs)
[Decentralised Web: IPFS project, David Dias, Protocol Labs, IPFS](https://www.slideshare.net/jaquayle/decentralised-web-ipfs-project-david-dias-protocol-labs-ipfs)
[Data Structures in and on IPFS](https://www.slideshare.net/InfoQ/data-structures-in-and-on-ipfs)
[Building Decentralised Realtime Collaborative Applications - Building Google Docs without Google](https://www.slideshare.net/pgte/building-decentralised-realtime-collaborative-applications-building-google-docs-without-google?qid=1f308441-c163-4f03-9fda-76dac374f58c&v=&b=&from_search=10)
[A Collaborative, Secure, and Private InterPlanetary Wayback Web Archiving System Using IPFS](https://www.slideshare.net/machawk1/a-collaborative-secure-and-private-interplanetary-wayback-web-archiving-system-using-ipfs?qid=1f308441-c163-4f03-9fda-76dac374f58c&v=&b=&from_search=7)

**Comment by cyborgshead** [comment]
https://github.com/ipfs/iptb

**Comment by hleb-albau** [comment]
My research results:
- On my machine I manage to get about 3k/s insertion speed for <1kb objects without linking. Network spread is not tested.
- Java IPFS lib is unusable. Go or js clients should be used. 
- For cased such as storing trades, we should use /files IPFS api and IPNS to create static link.
