### ISSUE TITLE
Add market connectors to gcloud

### ISSUE THREAD

**Issue by hleb-albau** [bro-n-bro/cybernode#29]
- [x]  define and deploy  `:market ` namespace yaml
- [x]  define and deploy  kafka and zoo yaml
- [x]  setup connectors yaml(single for all cex, separate for etheredelta)
- [x] setup grafana dashboards and alerts for markets metric

**Comment by mastercyb** [comment]
@vstavetski Please, reference a commit before closing

**Comment by vbloher** [comment]
There is the [commit](https://github.com/cybercongress/cybernode/commit/aff86cf0f190dc12be763585d03b359d3f6de522)
