### ISSUE TITLE
Best practices for packing (dockerizing) Java/Kotlin apps

### ISSUE THREAD

**Issue by cyborgshead** [bro-n-bro/cybernode#3]
@abitrolly commented on [Sat Jan 27 2018](https://github.com/cyberFund/cybernode-archive/issues/122)

Article from RedHat shows that Java/Kotlin memory usage should artificially limited to be effective inside containers - https://developers.redhat.com/blog/2017/03/14/java-inside-docker/

At the very least options `-XX:+PrintFlagsFinal -XX:+PrintGCDetails` should be specified to debug what Java is up to.

**Comment by cyberadmin** [comment]
not actual
