### ISSUE TITLE
Develop and describe name convention for cybernode's containers

### ISSUE THREAD

**Issue by cyborgshead** [bro-n-bro/cybernode#5]

**Comment by cyborgshead** [comment]
@hleb-albau need to clean up the convenction right now about containers
basic what we have are cs, cm, cn
- [x] cs-chain-pumps
- [x] cs-search-api
- [ ] cui-browser -> cyber-browser
- [x] cm-stream-api
- [x] cm-tickers
- [x] cm-rest-api
- [x] cm-connectors-___
- [x] chaingear-api
- [ ] address-service -> cs-address-service
- [x] cn-kafka-connectors
- [ ] cn-bitcoin-bitcoincore
- [ ] cn-ethereum-parity
also need to clean up all nonuseful containers at docker hub

**Comment by abitrolly** [comment]
My proposal. Search containers.

* cybernode/browser
* cybernode/index-engine - indexation service with API (cyber-search)
* cybernode/index-pumps - pumps (cyber-search)
* cybernode/index-address

Markets.
* cybernode/markets-streams - websockets service with API (cyber-markets)
* cybernode/markets-rest - REST service with API (cyber-markets)
* cybernode/markets-tickers - ???
* cybernode/exchange-___ - connectors to specific exchanges

Chaingear.
* cybernode/chaingear

Everything else.
* cybernode/kafka-connectors - ???
* cybernode/chain-btc-bitcoincore
* cybernode/chain-eth-parity

**Comment by cyborgshead** [comment]
@hleb-albau what is your opinion about conversion?

**Comment by abitrolly** [comment]
Our container naming convention.

    <subsystem>-<role>-<action>

* subsystems
  * chain - components fetching information from blockchain nodes
    * chain-pump - from node to kafka (queue)
      * chain-pump-eth
      * chain-pump-etc
      * chain-pump-btc
      * chain-pump-abc
    * chain-dump - from kafka to elassandra (indexed db)
      * chain-dump-eth
      * chain-dump-etc
      * chain-dump-btc
      * chain-dump-abc
    * chain-api - native api for development
      * chain-api-eth
      * chain-api-etc
      * chain-api-btc
      * chain-api-abc
    * chain-address - address-specific block/transaction processing
      * chain-address-eth
  * exchange - components fetching information from exchanges (markets)
    * exchange-pump-bitstamp
    * exchange-pump-hitbtc
    * exchange-pump-bitfinex
    * exchange-pump-poloniex
    * exchange-pump-gdax
    * exchange-pump-etherdelta
    * exchange-tickers - recalculating tickers from trade data

  * browser - user interface

  * engine - components for 
    * engine-api-chains - info from indexed chains
    * engine-api-markets - info from indexed markets

The following containers are used natively for our `index engine`:
  * confluentinc/cp-zookeeper
  * confluentinc/cp-kafka
  * hlebalbau/kafka-manager - dockerized `yahoo/kafka-manager` for debugging kafka queues
  * strapdata/elassandra

**Comment by abitrolly** [comment]
@hleb-albau so that is the resolution for this?
