### ISSUE TITLE
Run own ipfs node in cloud

### ISSUE THREAD

**Issue by Pechalka** [bro-n-bro/cybernode#79]
1 run ipfs node in cloud service
2 update link in cyb and cyb cli

**Comment by hleb-albau** [comment]
Done.
Use command below to get localhost access on cloud ipfs node.
```
kubectl port-forward -n chains $(kubectl get pod -n chains -l chain=ipfs -o jsonpath="{.items[0].metadata.name}") 5001 8080
```
Read only gateway enabled  on ipfs.cyb.ai
Example of app: http://ipfs.cyb.ai/ipfs/QmRFmPsihthoDf6ZnahxDs8y2y5upMF1CABRPagf9hwAnc/
