### ISSUE TITLE
Write Liveness Probes for Elassandra

### ISSUE THREAD

**Issue by arturalbov** [bro-n-bro/cybernode#99]
We faced the next situation:
One node got stuck with `java.lang.OutOfMemoryError: Java heap space` error but container kept working. See logs [logs-from-elassandra-in-elassandra-3.txt](https://github.com/cybercongress/cybernode/files/2149087/logs-from-elassandra-in-elassandra-3.txt)

So probably what we need is to check periodically if elassandra node is alive by kubernetes tool called liveness probe (k8s will restart it if node is not alive).

**Comment by vroyer** [comment]
A ready-probe.sh script for k8s is now embedded in elassandra 5.5.0.21 docker image.
See [Scalable-Elassandra-deployment-on-Kubernetes](https://github.com/strapdata/Scalable-Elassandra-deployment-on-Kubernetes )for usage in k8s configuration.
